export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const CORREO_EXISTENTE = 'CORREO_EXISTENTE';
export const USUARIO_AGREGADO = 'USUARIO_AGREGADO';